// SehatAI — Blog API (health education content)
// GET /api/blog?category=&limit= → list blog posts
// GET /api/blog?slug= → single post
import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

export const runtime = 'nodejs';

// Seed posts if none exist
async function seedIfEmpty() {
  const count = await db.blogPost.count();
  if (count > 0) return;
  const posts = [
    { slug: 'monsoon-diseases-pakistan', title: '5 Common Monsoon Diseases in Pakistan & How to Prevent Them', excerpt: 'Dengue, malaria, cholera, typhoid, and gastroenteritis spike during monsoon. Here\'s how to stay safe.', content: '## Monsoon Health Risks\n\nDuring the monsoon season (July-September), Pakistan sees a spike in water-borne and mosquito-borne diseases...\n\n### 1. Dengue Fever\nDengue is transmitted by Aedes mosquitoes...\n\n### 2. Malaria\nMalaria is endemic in Pakistan...', category: 'seasonal', tags: JSON.stringify(['dengue', 'malaria', 'monsoon', 'prevention']) },
    { slug: 'desi-diet-diabetes', title: 'Managing Diabetes with a Desi Diet: Pakistani Food Guide', excerpt: 'You don\'t need to give up biryani. Learn how to manage blood sugar with traditional Pakistani foods.', content: '## Diabetes & Pakistani Cuisine\n\nLiving with diabetes in Pakistan doesn\'t mean abandoning your cultural foods...\n\n### Best Foods\n- Roti (whole wheat) over naan\n- Daal (lentils)\n- Sabzi (vegetables)\n\n### Foods to Limit\n- Biryani (high glycemic)\n- Sweets (gulab jamun, jalebi)', category: 'nutrition', tags: JSON.stringify(['diabetes', 'diet', 'nutrition', 'pakistani-food']) },
    { slug: 'heat-stroke-prevention', title: 'Heat Stroke: Symptoms, Prevention & First Aid', excerpt: 'Pakistan\'s summers can reach 50°C. Learn to recognize heat stroke and save lives.', content: '## Heat Stroke\n\nHeat stroke is a medical emergency...\n\n### Symptoms\n- Body temperature above 40°C\n- Hot, dry skin\n- Confusion\n- Loss of consciousness\n\n### First Aid\n1. Move to shade\n2. Cool with water\n3. Call 1122', category: 'emergency', tags: JSON.stringify(['heat-stroke', 'summer', 'emergency', 'first-aid']) },
    { slug: 'pregnancy-nutrition-pakistan', title: 'Pregnancy Nutrition: A Pakistani Mother\'s Guide', excerpt: 'What to eat during each trimester — with Pakistani foods that provide the right nutrients.', content: '## Pregnancy Nutrition\n\n### First Trimester\n- Folic acid: Palak (spinach), daal\n- Iron: Red meat, beetroot\n\n### Second Trimester\n- Calcium: Milk, yogurt (dahi)\n- Protein: Eggs, chicken, daal\n\n### Third Trimester\n- Omega-3: Fish (if available)\n- Fiber: Vegetables, fruits', category: 'maternal', tags: JSON.stringify(['pregnancy', 'nutrition', 'maternal-health']) },
    { slug: 'child-vaccination-schedule', title: 'EPI Vaccination Schedule for Children in Pakistan', excerpt: 'Complete guide to Pakistan\'s Expanded Programme on Immunization (EPI) — when to get which vaccine.', content: '## EPI Schedule\n\n### At Birth\n- BCG (Tuberculosis)\n- OPV-0 (Polio)\n\n### 6 Weeks\n- Penta-1 (DPT, Hep B, Hib)\n- OPV-1\n- PCV-1\n\n### 10 Weeks\n- Penta-2, OPV-2, PCV-2\n\n### 14 Weeks\n- Penta-3, OPV-3, PCV-3\n\n### 9 Months\n- Measles-1\n\n### 15 Months\n- Measles-2', category: 'child-health', tags: JSON.stringify(['vaccination', 'children', 'EPI', 'immunization']) },
    { slug: 'hypertension-management', title: 'High Blood Pressure: Managing Hypertension in Pakistan', excerpt: '1 in 3 Pakistani adults has hypertension. Learn to manage it with lifestyle changes and medication.', content: '## Hypertension\n\n### Understanding BP Readings\n- Normal: below 120/80\n- Elevated: 120-129/80\n- High: 130+/80+\n\n### Lifestyle Changes\n1. Reduce salt (namak) intake\n2. Exercise 30 min daily\n3. Quit smoking\n4. Limit tea/coffee\n5. Manage stress', category: 'chronic', tags: JSON.stringify(['hypertension', 'blood-pressure', 'chronic-disease']) },
    { slug: 'dengue-prevention-pakistan', title: 'Dengue Fever: Symptoms, Prevention & Treatment', excerpt: 'Dengue outbreaks occur every monsoon in Pakistan. Learn to recognize symptoms and protect your family.', content: '## Dengue Fever\n\n### Symptoms\n- High fever (sudden onset)\n- Severe headache (especially behind eyes)\n- Joint and muscle pain ("breakbone fever")\n- Nausea/vomiting\n- Skin rash (2-5 days after fever)\n- Mild bleeding (nose, gums)\n\n### Warning Signs (Go to Hospital IMMEDIATELY)\n- Severe abdominal pain\n- Persistent vomiting\n- Bleeding from gums/nose\n- Blood in vomit/stool\n- Difficulty breathing\n- Cold/clammy skin\n- Restlessness or drowsiness\n\n### Prevention\n1. Remove standing water (flower pots, tires, coolers)\n2. Use mosquito repellent\n3. Wear long sleeves/pants\n4. Use mosquito nets while sleeping\n5. Keep windows/doors screened\n\n### Treatment\n- No specific antiviral — supportive care only\n- Drink plenty of fluids (water, soup, juice)\n- Paracetamol for fever (NEVER aspirin/ibuprofen — bleeding risk!)\n- Rest\n- Go to hospital if warning signs appear', category: 'seasonal', tags: JSON.stringify(['dengue', 'mosquito', 'monsoon', 'fever', 'prevention']) },
    { slug: 'diabetes-type-2-pakistan', title: 'Type 2 Diabetes: A Growing Crisis in Pakistan', excerpt: 'Pakistan has one of the highest diabetes rates in the world. Learn symptoms, management, and prevention.', content: '## Type 2 Diabetes\n\nPakistan ranks among the top 10 countries for diabetes prevalence. 1 in 4 adults over 20 may be affected.\n\n### Symptoms\n- Excessive thirst (polydipsia)\n- Frequent urination (polyuria)\n- Increased hunger\n- Unexplained weight loss\n- Fatigue\n- Blurred vision\n- Slow-healing wounds\n- Frequent infections\n\n### Risk Factors\n- Family history\n- Overweight/obesity\n- Sedentary lifestyle\n- Age over 35\n- High-sugar diet\n- Gestational diabetes history\n\n### Management\n1. **Blood sugar monitoring** — check fasting and post-meal\n2. **Diet** — reduce sugar, increase fiber, whole grains\n3. **Exercise** — 30 minutes brisk walk daily\n4. **Medication** — metformin (first-line), as prescribed\n5. **HbA1c** — check every 3 months\n\n### Desi Diet Tips\n- Replace white rice with brown rice or roti\n- Reduce roti quantity, increase sabzi\n- Avoid sugary chai — use less or no sugar\n- Eat daal instead of meat-heavy curries\n- Snack on roasted chana instead of samosas\n\n### Emergency\n- Low sugar (hypoglycemia): sweating, shaking, confusion → eat sugar immediately\n- High sugar (DKA): vomiting, fruity breath, deep breathing → hospital immediately', category: 'chronic', tags: JSON.stringify(['diabetes', 'sugar', 'blood-glucose', 'insulin', 'metformin', 'chronic-disease']) },
    { slug: 'safe-water-pakistan', title: 'Safe Drinking Water: Preventing Waterborne Diseases', excerpt: 'Contaminated water causes cholera, typhoid, hepatitis A. Learn how to make water safe.', content: '## Safe Drinking Water\n\n### Why It Matters\nWaterborne diseases kill thousands of Pakistanis yearly. Contaminated water spreads: cholera, typhoid, hepatitis A, diarrhea, dysentery, polio.\n\n### How to Make Water Safe\n\n**Boiling (most reliable):**\n- Bring water to a rolling boil for 1 minute\n- At high altitude (>2000m): boil for 3 minutes\n- Store in clean, covered container\n\n**Filtration:**\n- Use a certified water filter (NSF/WHO approved)\n- Replace filters as recommended\n- Ceramic filters remove bacteria and parasites\n\n**Chlorination:**\n- Add 2 drops of household bleach (5%) per liter\n- Wait 30 minutes before drinking\n- Water should have slight chlorine smell\n\n**Solar disinfection (SODIS):**\n- Fill clear PET bottle with water\n- Place in direct sunlight for 6 hours\n- Effective against most pathogens\n\n### What to Avoid\n- Don\'t drink from taps without treatment\n- Don\'t use water from wells near sewage\n- Avoid ice made from untreated water\n- Don\'t store water in dirty containers\n\n### During Floods\n- Flood water is extremely contaminated\n- Use only boiled or bottled water\n- Do NOT drink from flooded wells without testing\n- Use ORS if diarrhea develops', category: 'nutrition', tags: JSON.stringify(['water', 'cholera', 'typhoid', 'hepatitis', 'diarrhea', 'prevention', 'hygiene']) },
    { slug: 'mental-health-pakistan', title: 'Mental Health in Pakistan: Breaking the Stigma', excerpt: 'Depression and anxiety are common but treatable. Don\'t suffer in silence.', content: '## Mental Health\n\n### The Reality\n- 1 in 4 Pakistanis will experience a mental health condition\n- Depression is the leading cause of disability\n- Suicide rates are rising, especially in youth\n- Stigma prevents 80% from seeking help\n\n### Common Conditions\n\n**Depression:**\n- Persistent sadness, loss of interest\n- Changes in sleep/appetite\n- Fatigue, difficulty concentrating\n- Feelings of worthlessness\n- Thoughts of death/suicide\n\n**Anxiety:**\n- Excessive worry\n- Restlessness, irritability\n- Panic attacks (sudden fear, heart racing, shortness of breath)\n- Avoidance of situations\n\n### Where to Get Help\n1. **Psychiatrist** — medical doctor who can prescribe medication\n2. **Psychologist** — therapy (CBT, counseling)\n3. **Helplines:**\n   - 1166 (Health Helpline — mental health support)\n   - 1099 (Women Helpline)\n   - Umang Helpline: 0311-7786264\n4. **Hospital emergency** — if suicidal or in crisis\n\n### Self-Care Tips\n1. Talk to someone you trust\n2. Exercise daily (even 15 min walk)\n3. Sleep 7-8 hours\n4. Eat regular meals\n5. Reduce caffeine and avoid drugs/alcohol\n6. Practice deep breathing or meditation\n7. Set small, achievable goals\n8. Stay connected with family/friends\n\n### If Someone is Suicidal\n- Take them seriously — never dismiss\n- Ask directly: "Are you thinking about suicide?"\n- Remove access to means\n- Stay with them\n- Call 1122 or take to hospital\n- Don\'t leave them alone\n\n**Mental illness is NOT weakness. It is a medical condition. Treatment works.**', category: 'mental-health', tags: JSON.stringify(['depression', 'anxiety', 'suicide', 'mental-health', 'therapy', 'psychiatry', 'stigma']) },
    { slug: 'polio-eradication-pakistan', title: 'Polio: Pakistan\'s Fight Against the Last Frontier', excerpt: 'Pakistan is one of only 2 countries with wild polio. Learn why vaccination is critical.', content: '## Polio Eradication\n\nPakistan and Afghanistan are the only countries where wild poliovirus still circulates.\n\n### What is Polio?\nPoliomyelitis is a viral infection that can cause permanent paralysis, especially in children under 5.\n\n### Symptoms\n- Most infections have NO symptoms\n- Mild: fever, sore throat, headache, vomiting\n- Severe: neck stiffness, muscle weakness, paralysis (usually legs)\n- Paralysis can be permanent\n\n### Prevention — VACCINATION IS THE ONLY WAY\n\n**OPV (Oral Polio Vaccine):**\n- Given as drops in the mouth\n- Schedule: at birth, 6, 10, 14 weeks, and 9 months\n- Safe, effective, free at all EPI centers\n\n**Why multiple doses?**\n- Each dose boosts immunity\n- In areas with poor sanitation, more doses needed\n- Even if your child received drops before, EVERY campaign dose is important\n\n### Common Myths (FALSE)\n- "Vaccine causes infertility" — FALSE, no scientific evidence\n- "Vaccine is not halal" — FALSE, certified by Islamic scholars worldwide\n- "My child is already vaccinated" — still give campaign doses for extra protection\n- "Polio is God\'s will" — FALSE, it\'s preventable through vaccination\n\n### If You See Paralysis\nAny child under 15 with sudden weakness/paralysis = go to hospital IMMEDIATELY. Report to health department.\n\n**Every child, every dose, every campaign — until polio is gone.**', category: 'child-health', tags: JSON.stringify(['polio', 'vaccine', 'immunization', 'EPI', 'paralysis', 'children', 'eradication']) },
    { slug: 'smoking-cessation-pakistan', title: 'Quitting Smoking: Your Guide to a Tobacco-Free Life', excerpt: 'Smoking kills 160,000 Pakistanis yearly. It\'s never too late to quit.', content: '## Quitting Smoking\n\n### The Facts\n- 160,000+ Pakistanis die from tobacco-related diseases yearly\n- 1 in 5 adults in Pakistan uses tobacco\n- Shisha/huqqa is as harmful as cigarettes\n- Gutka, paan, naswar cause oral cancer\n\n### Health Benefits of Quitting\n- **Within 20 min:** blood pressure drops\n- **Within 24 hours:** heart attack risk decreases\n- **Within 48 hours:** taste/smell improve\n- **Within 2 weeks:** circulation improves\n- **Within 1 year:** heart disease risk halves\n- **Within 5 years:** stroke risk = non-smoker\n\n### How to Quit\n\n**Step 1: Set a Quit Date**\nChoose a date within 2 weeks. Tell family/friends.\n\n**Step 2: Identify Triggers**\n- After meals? While driving? When stressed?\n- Plan alternatives for each trigger\n\n**Step 3: Nicotine Replacement**\n- Nicotine gum/patches (available at pharmacies)\n- Reduces withdrawal symptoms\n- Use for 8-12 weeks, then taper\n\n**Step 4: Behavioral Changes**\n- Drink water when craving hits\n- Exercise or walk\n- Chew sugar-free gum\n- Call a friend for support\n- Avoid places where others smoke\n\n**Step 5: Medical Help**\n- Bupropion (Zyban) — prescription medication\n- Varenicline (Chantix) — prescription medication\n- Counseling/support groups\n\n### Withdrawal Symptoms (normal, pass in 2-4 weeks)\n- Irritability, anxiety\n- Difficulty concentrating\n- Increased appetite\n- Insomnia\n- Strong cravings\n\n**Don\'t give up. Most people try 5-7 times before quitting for good. Each attempt brings you closer.**', category: 'chronic', tags: JSON.stringify(['smoking', 'tobacco', 'cessation', 'cancer', 'lung-disease', 'addiction']) },
    { slug: 'winter-health-pakistan', title: 'Winter Health Tips: Surviving the Cold Season', excerpt: 'Winter brings its own health challenges in Pakistan. Stay healthy with these tips.', content: '## Winter Health\n\n### Common Winter Problems in Pakistan\n\n**1. Respiratory Infections**\n- Common cold, flu, chest infections increase\n- Children and elderly most at risk\n- Prevention: wash hands, avoid crowds, stay warm\n- Treatment: rest, fluids, paracetamol. See doctor if breathing difficulty.\n\n**2. Carbon Monoxide Poisoning**\n- Gas heaters in closed rooms = SILENT KILLER\n- Symptoms: headache, dizziness, nausea, drowsiness, confusion\n- Prevention: ALWAYS keep a window open when using gas heater\n- EMERGENCY: turn off heater, open windows, go outside, call 1122\n\n**3. Dry Skin**\n- Cold + dry air = itchy, cracked skin\n- Prevention: moisturize daily, drink water, use lukewarm (not hot) water\n\n**4. Asthma/COPD Flare-ups**\n- Cold air triggers breathing problems\n- Prevention: cover nose/mouth with scarf, use inhaler regularly, avoid cold air directly\n\n**5. Hypothermia**\n- Especially in northern areas (Gilgit, Skardu, Quetta)\n- Symptoms: shivering, confusion, drowsiness, cold skin\n- Prevention: wear layers, cover head/feet, warm room\n- EMERGENCY: gradual warming, warm drinks, hospital\n\n### Winter Diet Tips\n- Eat warm foods: soup, halim, nihari\n- Drink warm water with honey/lemon\n- Increase vitamin C (citrus fruits: malta, kinnow, oranges)\n- Dry fruits (almonds, walnuts) for energy\n- Ginger tea (adrak wali chai) for immunity\n\n### Vaccination\n- Get flu vaccine (especially elderly, children, pregnant women, chronic disease patients)\n- Pneumococcal vaccine for elderly', category: 'seasonal', tags: JSON.stringify(['winter', 'flu', 'carbon-monoxide', 'asthma', 'cold', 'health-tips']) },
    { slug: 'first-aid-basics-everyone-should-know', title: 'First Aid Basics Every Pakistani Should Know', excerpt: 'You could save a life. Learn these essential first aid skills.', content: '## First Aid Basics\n\n### 1. Burns\n- **Immediately:** cool with running water for 20 minutes\n- Remove jewelry/tight clothing near burn\n- Cover with clean cloth\n- **DO NOT:** apply toothpaste, oil, ice, or butter\n- **Hospital if:** large area, face, hands, genitals, or child\n\n### 2. Bleeding\n- Apply firm pressure with clean cloth\n- Elevate the wound above heart level\n- Keep pressing for 10 minutes minimum\n- **DO NOT:** remove embedded objects — pad around them\n- **Hospital if:** bleeding doesn\'t stop, deep wound, or arterial bleeding (spurting blood)\n\n### 3. Choking (Heimlich Maneuver)\n- Ask: "Are you choking?" If they can\'t speak/breathe\n- Stand behind them, wrap arms around waist\n- Make a fist above navel, other hand on top\n- Thrust inward and upward 5 times\n- Repeat until object is dislodged or person collapses\n- If unconscious: start CPR, call 1122\n\n### 4. Seizure\n- **DO:** clear area of hard objects, cushion head, turn on side\n- **DO NOT:** hold them down, put anything in mouth, give water\n- Time the seizure\n- Call 1122 if: seizure > 5 min, no recovery, first seizure, pregnant, or injured\n\n### 5. Fracture\n- Don\'t move the injured limb\n- Immobilize with a splint (stick, rolled newspaper)\n- Apply cold compress (not ice directly)\n- Transport carefully to hospital\n\n### 6. Nosebleed\n- Sit upright, lean FORWARD (not back)\n- Pinch nostrils for 10 minutes\n- Breathe through mouth\n- Don\'t blow nose for 1 hour\n- Hospital if: bleeding > 20 min, heavy bleeding, or after head injury\n\n### 7. Snake/Scorpion Bite\n- Keep person calm and still\n- Keep bitten limb below heart\n- Go to hospital immediately\n- **DO NOT:** cut, suck, ice, or tourniquet\n\n### 8. Heat Stroke\n- Move to shade\n- Remove clothing\n- Cool with water (spray, wet cloth)\n- Fan vigorously\n- Call 1122 — this is an emergency\n\n### 9. Fainting\n- Lay person flat, elevate legs\n- Loosen tight clothing\n- Check breathing\n- If not breathing: start CPR, call 1122\n\n### 10. Bee/Wasp Sting\n- Remove stinger by scraping (not squeezing)\n- Wash with soap\n- Apply cold compress\n- Watch for allergic reaction (swelling, breathing difficulty = emergency)\n\n**Remember: In any emergency, call 1122 (Rescue), 1166 (Health Helpline), or 115 (Edhi).**', category: 'emergency', tags: JSON.stringify(['first-aid', 'emergency', 'burns', 'bleeding', 'choking', 'seizure', 'cpr', 'save-life']) },
    { slug: 'breastfeeding-guide-pakistan', title: 'Breastfeeding: The Best Start for Your Baby', excerpt: 'WHO recommends exclusive breastfeeding for 6 months. Learn proper technique and benefits.', content: '## Breastfeeding\n\n### Why Breastfeeding Matters\n- Protects baby from infections (diarrhea, pneumonia, ear infections)\n- Reduces mother\'s risk of breast/ovarian cancer\n- Builds emotional bond\n- FREE — no cost, no preparation\n- Perfect nutrition for baby\n\n### WHO Recommendations\n1. **Exclusive breastfeeding** for first 6 months (no water, no formula, no honey)\n2. **Start within 1 hour** of birth\n3. **Continue** with complementary foods up to 2 years+\n4. **On-demand feeding** — whenever baby is hungry (8-12 times/24 hours)\n\n### Proper Technique\n- Baby\'s whole body faces mother (not just head)\n- Baby\'s mouth covers ENTIRE areola (dark area), not just nipple\n- Lips flanged outward (like fish lips)\n- Listen for swallowing sounds\n- No pain for mother (if painful, reposition)\n\n### Signs Baby is Getting Enough\n- 6+ wet diapers per day\n- 3+ yellow stools per day (after day 4)\n- Baby is calm and satisfied after feeding\n- Steady weight gain\n- Baby sleeps well between feeds\n\n### Common Problems\n\n**Sore nipples:** Check positioning. Apply breast milk to nipples, air dry.\n\n**Engorgement (swollen, painful breasts):** Feed frequently, warm compress before feeding, cold compress after.\n\n**Mastitis (breast infection):** Red, painful, swollen area + fever. Continue breastfeeding. See doctor for antibiotics.\n\n**Low milk supply:** Feed more often, drink plenty of water, rest. Supply increases with demand.\n\n### What to Avoid\n- No formula/water in first 6 months\n- No pacifiers in first 4 weeks (nipple confusion)\n- Avoid smoking, alcohol, excessive caffeine\n- Some medications pass into milk — always check with doctor\n\n### Working Mothers\n- Express breast milk (hand or pump)\n- Store: room temp (4 hr), refrigerator (72 hr), freezer (3 months)\n- Label with date/time\n- Thaw in warm water, never microwave\n\n**Breast milk is the perfect food. Every drop counts.**', category: 'maternal', tags: JSON.stringify(['breastfeeding', 'newborn', 'maternal', 'nutrition', 'baby-care', 'WHO']) },
    { slug: 'dengue-vs-malaria-difference', title: 'Dengue vs Malaria: How to Tell the Difference', excerpt: 'Both cause fever but need different treatment. Learn to recognize which is which.', content: '## Dengue vs Malaria\n\nBoth are mosquito-borne diseases common in Pakistan, but they have important differences.\n\n### Comparison Table\n\n| Feature | Dengue | Malaria |\n|---|---|---|\n| Mosquito | Aedes (day-biting) | Anopheles (night-biting) |\n| Onset | Sudden high fever | Gradual fever |\n| Fever pattern | Continuous high | Cyclical (fever → no fever → fever) |\n| Headache | Severe (behind eyes) | Moderate |\n| Body pain | Severe joint/muscle ("breakbone") | Moderate |\n| Rash | Yes (2-5 days) | No |\n| Bleeding | Yes (nose, gums, skin) | No |\n| Chills | Mild | Severe (shaking) |\n| Sweating | Mild | Profuse |\n| Incubation | 4-10 days | 7-30 days |\n\n### When to Get Tested\n- **Dengue:** NS1 antigen test (first 5 days), IgM (after 5 days)\n- **Malaria:** Blood smear (thick and thin film)\n\n### Treatment\n\n**Dengue:**\n- NO specific treatment — supportive only\n- Paracetamol for fever (NEVER aspirin/ibuprofen — bleeding risk!)\n- Plenty of fluids\n- Monitor platelet count\n- Hospital if: warning signs (abdominal pain, persistent vomiting, bleeding, drowsiness)\n\n**Malaria:**\n- Antimalarial medication (artemisinin-based combination therapy — ACT)\n- Must be prescribed by doctor after confirming diagnosis\n- Complete full course of medication\n- Hospital if: severe malaria (convulsions, unconscious, severe anemia, kidney failure)\n\n### Prevention\n\n**Dengue prevention:**\n- Remove standing water (Aedes breeds in clean water)\n- Use repellent during daytime\n- Full-sleeve clothing\n\n**Malaria prevention:**\n- Use mosquito nets at night (Anopheles bites at night)\n- Insecticide-treated bed nets\n- Repellent at night\n- Antimalarial prophylaxis if traveling to high-risk area\n\n**If you have fever during monsoon season, get tested for BOTH dengue and malaria.**', category: 'seasonal', tags: JSON.stringify(['dengue', 'malaria', 'fever', 'mosquito', 'monsoon', 'comparison', 'diagnosis']) },
  ];
  for (const p of posts) {
    await db.blogPost.create({ data: p });
  }
}

export async function GET(req: NextRequest) {
  await seedIfEmpty();
  const url = new URL(req.url);
  const slug = url.searchParams.get('slug');
  const category = url.searchParams.get('category');
  const limit = Math.min(50, parseInt(url.searchParams.get('limit') ?? '10'));

  if (slug) {
    const post = await db.blogPost.findUnique({ where: { slug } });
    if (!post) return NextResponse.json({ error: 'Post not found' }, { status: 404 });
    return NextResponse.json({ post: { ...post, tags: JSON.parse(post.tags) } });
  }

  const where = category ? { category } : {};
  const posts = await db.blogPost.findMany({
    where,
    orderBy: { publishedAt: 'desc' },
    take: limit,
  });
  return NextResponse.json({
    posts: posts.map(p => ({ ...p, tags: JSON.parse(p.tags) })),
  });
}
