'use client';

import { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Share2,
  Printer,
  MessageCircle,
  ClipboardCopy,
  X,
  FileText,
  Check,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { resolveUiLang, t } from '@/lib/i18n';
import type { ChatMessage, Lang, TriageLevel } from '@/lib/types';
import { cn } from '@/lib/utils';

// ============================================================
// SehatAI — Enhanced Chat Export (Phase 2)
// Exports the conversation transcript in 3 ways:
//   1. Copy to clipboard (existing)
//   2. Share to WhatsApp (pre-filled message)
//   3. Print / Save as PDF (print-optimized layout)
//
// Safety: the export includes the SehatAI disclaimer ("not a
// diagnosis — consult a doctor") at the top + bottom.
// ============================================================

interface ChatExportMenuProps {
  messages: ChatMessage[];
  lang: Lang;
  className?: string;
}

export function ChatExportMenu({ messages, lang, className }: ChatExportMenuProps) {
  const { toast } = useToast();
  const [open, setOpen] = useState(false);

  const buildTranscript = useCallback(() => {
    const lines = messages.map((m) => {
      const who = m.role === 'user' ? t(lang, 'chat.you') : t(lang, 'chat.assistant');
      const triage = m.triage?.level ? ` [${m.triage.level}]` : '';
      const confidence = m.confidence ? ` (${m.confidence.band} confidence)` : '';
      return `${who}${triage}${confidence}: ${m.content}`;
    });
    const disclaimer = lang === 'ur'
      ? '⚠️ سی ایچ اے آئی تشخیص نہیں دیتا — ڈاکٹر سے مشورہ کریں۔'
      : lang === 'roman'
        ? '⚠️ SehatAI tashkhees nahi deta — doctor se mashwara karein.'
        : '⚠️ SehatAI does not diagnose — consult a doctor.';
    const header = `SehatAI — ${t(lang, 'chat.transcript') || 'Conversation transcript'}\n${new Date().toLocaleString()}\n${disclaimer}\n\n`;
    const footer = `\n\n${disclaimer}\nGenerated by SehatAI — Safety-first health guidance for Pakistan`;
    return header + lines.join('\n\n') + footer;
  }, [messages, lang]);

  const copyToClipboard = useCallback(async () => {
    if (messages.length === 0) return;
    try {
      await navigator.clipboard.writeText(buildTranscript());
      toast({ description: t(lang, 'chat.transcriptCopied') || 'Copied to clipboard' });
    } catch {
      toast({ description: 'Copy failed', variant: 'destructive' });
    }
  }, [messages, buildTranscript, toast, lang]);

  const shareWhatsApp = useCallback(() => {
    if (messages.length === 0) return;
    const text = buildTranscript();
    // WhatsApp has a URL length limit (~2000 chars for wa.me links)
    const truncated = text.length > 2000 ? text.slice(0, 2000) + '\n...(truncated)' : text;
    const url = `https://wa.me/?text=${encodeURIComponent(truncated)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  }, [messages, buildTranscript]);

  const printTranscript = useCallback(() => {
    if (messages.length === 0) return;
    const printWindow = window.open('', '_blank', 'noopener,noreferrer');
    if (!printWindow) {
      toast({ description: 'Pop-up blocked — allow pop-ups to print', variant: 'destructive' });
      return;
    }
    const lines = messages.map((m) => {
      const who = m.role === 'user' ? t(lang, 'chat.you') : t(lang, 'chat.assistant');
      const triage = m.triage?.level ? ` <span class="triage ${m.triage.level}">${m.triage.level}</span>` : '';
      const conf = m.confidence ? ` <span class="conf">${m.confidence.band} confidence</span>` : '';
      return `<div class="msg ${m.role}"><span class="who">${who}${triage}${conf}</span><p>${escapeHtml(m.content)}</p></div>`;
    }).join('');
    const disclaimer = lang === 'ur'
      ? 'سی ایچ اے آئی تشخیص نہیں دیتا — ڈاکٹر سے مشورہ کریں'
      : lang === 'roman'
        ? 'SehatAI tashkhees nahi deta — doctor se mashwara karein'
        : 'SehatAI does not diagnose — consult a doctor';
    const html = `<!DOCTYPE html>
<html lang="${lang === 'ur' ? 'ur' : 'en'}" dir="${lang === 'ur' ? 'rtl' : 'ltr'}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SehatAI — ${t(lang, 'chat.transcript') || 'Conversation transcript'}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 680px; margin: 0 auto; padding: 20px; color: #1a1a1a; }
  .header { text-align: center; border-bottom: 2px solid #14b8a6; padding-bottom: 10px; margin-bottom: 20px; }
  .header h1 { color: #0f766e; font-size: 18px; margin: 0; }
  .header p { color: #666; font-size: 11px; margin: 4px 0; }
  .disclaimer { background: #fef3c7; border: 1px solid #f59e0b; border-radius: 6px; padding: 8px 12px; font-size: 11px; margin: 10px 0; }
  .msg { margin-bottom: 12px; padding: 8px 12px; border-radius: 8px; page-break-inside: avoid; }
  .msg.user { background: #f0f9ff; border-left: 3px solid #0ea5e9; }
  .msg.assistant { background: #f0fdfa; border-left: 3px solid #14b8a6; }
  .who { font-size: 10px; font-weight: bold; color: #666; text-transform: uppercase; display: block; margin-bottom: 4px; }
  .msg p { margin: 0; font-size: 13px; line-height: 1.5; white-space: pre-wrap; }
  .triage { display: inline-block; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: bold; margin-left: 4px; }
  .triage.EMERGENCY { background: #fee2e2; color: #b91c1c; }
  .triage.URGENT { background: #ffedd5; color: #c2410c; }
  .triage.ROUTINE { background: #fef3c7; color: #b45309; }
  .triage.SELF_CARE { background: #d1fae5; color: #047857; }
  .conf { color: #6366f1; font-size: 9px; font-weight: normal; }
  .footer { text-align: center; font-size: 10px; color: #999; margin-top: 20px; padding-top: 10px; border-top: 1px solid #eee; }
  @media print { body { max-width: none; padding: 10px; } }
</style>
</head>
<body>
  <div class="header">
    <h1>SehatAI — ${t(lang, 'chat.transcript') || 'Conversation transcript'}</h1>
    <p>${new Date().toLocaleString()}</p>
  </div>
  <div class="disclaimer">⚠️ ${disclaimer}</div>
  ${lines}
  <div class="disclaimer">⚠️ ${disclaimer}</div>
  <div class="footer">Generated by SehatAI — Safety-first health guidance for Pakistan</div>
</body>
</html>`;
    printWindow.document.write(html);
    printWindow.document.close();
    // Wait for content to render, then trigger print
    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
    }, 500);
  }, [messages, lang, toast]);

  if (messages.length === 0) return null;

  return (
    <div className={cn('relative', className)}>
      <Button
        variant="ghost"
        size="sm"
        onClick={() => setOpen((v) => !v)}
        className="h-8 gap-1.5 px-2.5 text-xs font-medium text-muted-foreground hover:text-foreground"
        aria-label="Export conversation"
      >
        <Share2 className="h-3.5 w-3.5" aria-hidden />
        <span className="hidden sm:inline">{lang === 'ur' ? 'ایکسپورٹ' : lang === 'roman' ? 'Export' : 'Export'}</span>
      </Button>

      <AnimatePresence>
        {open ? (
          <motion.div
            initial={{ opacity: 0, y: -4, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -4, scale: 0.95 }}
            transition={{ duration: 0.15 }}
            className="absolute bottom-full right-0 z-30 mb-2 w-56 rounded-xl border border-border bg-card p-2 shadow-lg"
            role="menu"
            aria-label="Export options"
          >
            <div className="mb-1 flex items-center justify-between px-1">
              <p className="text-[10px] font-bold tracking-wider text-muted-foreground uppercase">
                {lang === 'ur' ? 'ایکسپورٹ' : lang === 'roman' ? 'Export' : 'Export'}
              </p>
              <button type="button" onClick={() => setOpen(false)} className="text-muted-foreground hover:text-foreground">
                <X className="h-3 w-3" aria-hidden />
              </button>
            </div>

            {/* Copy */}
            <button
              type="button"
              onClick={() => { void copyToClipboard(); setOpen(false); }}
              className="flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-start transition-colors hover:bg-accent/40"
            >
              <ClipboardCopy className="h-4 w-4 text-primary" aria-hidden />
              <span className="text-xs font-medium text-foreground">{lang === 'ur' ? 'کاپی' : lang === 'roman' ? 'Copy' : 'Copy'}</span>
            </button>

            {/* WhatsApp */}
            <button
              type="button"
              onClick={() => { shareWhatsApp(); setOpen(false); }}
              className="flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-start transition-colors hover:bg-accent/40"
            >
              <MessageCircle className="h-4 w-4 text-emerald-600" aria-hidden />
              <span className="text-xs font-medium text-foreground">{lang === 'ur' ? 'واٹس ایپ' : lang === 'roman' ? 'WhatsApp' : 'WhatsApp'}</span>
            </button>

            {/* Print / PDF */}
            <button
              type="button"
              onClick={() => { printTranscript(); setOpen(false); }}
              className="flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-start transition-colors hover:bg-accent/40"
            >
              <Printer className="h-4 w-4 text-slate-600" aria-hidden />
              <span className="text-xs font-medium text-foreground">{lang === 'ur' ? 'پرنٹ / PDF' : lang === 'roman' ? 'Print / PDF' : 'Print / PDF'}</span>
            </button>

            <div className="mt-1 border-t border-border/60 pt-1">
              <p className="px-1 text-[9px] leading-relaxed text-muted-foreground">
                {lang === 'ur'
                  ? 'ایکسپورٹ میں ڈس کلیمر شامل ہے — سی ایچ اے آئی تشخیص نہیں دیتا۔'
                  : lang === 'roman'
                    ? 'Export mein disclaimer shamil hai — SehatAI tashkhees nahi deta.'
                    : 'Exports include the SehatAI disclaimer — not a diagnosis.'}
              </p>
            </div>
          </motion.div>
        ) : null}
      </AnimatePresence>
    </div>
  );
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
