import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { llmJSON } from '@/server/llm';
import { hasDosePattern } from '@/server/pipeline/run';
import type { DoctorSummary, Lang, TriageLevel } from '@/lib/types';
import { TRIAGE_ORDER } from '@/lib/types';

export const runtime = 'nodejs';

const DISCLAIMER =
  'Generated by SehatAI — informational summary for the treating clinician. Not a diagnosis.';

const SUMMARY_SYSTEM = `You generate structured clinical handover summaries from a conversation between a Pakistani user/patient and SehatAI, a health guidance assistant.

Return ONLY valid JSON (no markdown fences):
{"chiefComplaint": string, "duration": string, "symptoms": string[], "redFlagsObserved": string[], "triageLevel": "SELF_CARE"|"ROUTINE"|"URGENT"|"EMERGENCY", "guidanceGiven": string[]}

Rules:
- chiefComplaint: one short English phrase describing the main complaint.
- duration: e.g. "2 days" or "not stated".
- symptoms: English symptom terms extracted from the conversation (max 10).
- redFlagsObserved: emergency danger signs mentioned by the user (English, max 10) — empty if none.
- triageLevel: the highest severity suggested across the conversation.
- guidanceGiven: 2-5 short English bullets of the guidance already given.
- NEVER include medicine doses or amounts. NEVER diagnose — report only what the user described.`;

interface MessageRow {
  id: string;
  role: string;
  content: string;
  language: string;
  triageLevel: string | null;
  redFlags: string | null;
  pipelineMeta: string | null;
  emergency: boolean;
  createdAt: Date;
}

function maxLevel(levels: TriageLevel[]): TriageLevel {
  return levels.reduce<TriageLevel>((acc, l) => (TRIAGE_ORDER[l] > TRIAGE_ORDER[acc] ? l : acc), 'SELF_CARE');
}

/** Deterministic summary built from stored pipeline metadata (used when LLM fails). */
function deterministicSummary(conversationId: string, rows: MessageRow[], lang: Lang): DoctorSummary {
  const userRows = rows.filter((r) => r.role === 'user');
  const assistantRows = rows.filter((r) => r.role === 'assistant');
  const firstUser = userRows[0]?.content ?? '';

  const symptoms: string[] = [];
  const redFlags: string[] = [];
  const levels: TriageLevel[] = [];
  for (const r of assistantRows) {
    if (r.triageLevel && ['SELF_CARE', 'ROUTINE', 'URGENT', 'EMERGENCY'].includes(r.triageLevel)) {
      levels.push(r.triageLevel as TriageLevel);
    }
    try {
      const meta = r.pipelineMeta ? (JSON.parse(r.pipelineMeta) as Record<string, unknown>) : null;
      const l1 = meta?.l1 as { symptoms?: string[]; redFlagConcerns?: string[] } | null | undefined;
      if (l1?.symptoms) for (const s of l1.symptoms) if (!symptoms.includes(s)) symptoms.push(s);
      if (l1?.redFlagConcerns) for (const s of l1.redFlagConcerns) if (!redFlags.includes(s)) redFlags.push(s);
    } catch {
      // ignore malformed meta
    }
    if (r.redFlags) {
      try {
        const parsed = JSON.parse(r.redFlags);
        if (Array.isArray(parsed)) {
          for (const f of parsed) {
            const cat = typeof f === 'object' && f ? String((f as { category?: unknown }).category ?? '') : '';
            if (cat && !redFlags.includes(cat)) redFlags.push(cat);
          }
        }
      } catch {
        // ignore
      }
    }
  }

  const durationDays = (() => {
    const durations: number[] = [];
    for (const r of assistantRows) {
      try {
        const meta = r.pipelineMeta ? (JSON.parse(r.pipelineMeta) as Record<string, unknown>) : null;
        const d = (meta?.l1 as { durationDays?: number | null } | null | undefined)?.durationDays;
        if (typeof d === 'number') durations.push(d);
      } catch {
        // ignore
      }
    }
    if (durations.length === 0) return 'not stated';
    const max = Math.max(...durations);
    return max === 1 ? '1 day' : `${max} days`;
  })();

  return {
    conversationId,
    chiefComplaint: firstUser ? firstUser.slice(0, 160) : 'No user messages in this conversation.',
    duration: durationDays,
    symptoms: symptoms.slice(0, 10),
    redFlagsObserved: redFlags.slice(0, 10),
    triageLevel: levels.length ? maxLevel(levels) : 'ROUTINE',
    guidanceGiven: assistantRows.slice(0, 4).map((r) => r.content.replace(/\s+/g, ' ').slice(0, 140)),
    language: lang,
    disclaimer: DISCLAIMER,
  };
}

function sanitizeSummary(raw: unknown, conversationId: string, lang: Lang): DoctorSummary | null {
  if (!raw || typeof raw !== 'object') return null;
  const r = raw as Record<string, unknown>;
  const levels: TriageLevel[] = ['SELF_CARE', 'ROUTINE', 'URGENT', 'EMERGENCY'];
  const str = (v: unknown, max: number) => (typeof v === 'string' ? v.trim().slice(0, max) : '');
  const strArr = (v: unknown, max: number) =>
    Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string' && x.trim().length > 0).map((x) => x.slice(0, 100)).slice(0, max) : [];

  const summary: DoctorSummary = {
    conversationId,
    chiefComplaint: str(r.chiefComplaint, 200),
    duration: str(r.duration, 60) || 'not stated',
    symptoms: strArr(r.symptoms, 10),
    redFlagsObserved: strArr(r.redFlagsObserved, 10),
    triageLevel: levels.includes(String(r.triageLevel).toUpperCase() as TriageLevel)
      ? (String(r.triageLevel).toUpperCase() as TriageLevel)
      : 'ROUTINE',
    guidanceGiven: strArr(r.guidanceGiven, 5),
    language: lang,
    disclaimer: DISCLAIMER,
  };
  if (!summary.chiefComplaint) return null;
  // hard validation: no doses anywhere in the summary
  if (hasDosePattern(JSON.stringify(summary))) return null;
  return summary;
}

/** POST /api/summary {conversationId, language?} → DoctorSummary */
export async function POST(req: NextRequest) {
  let body: { conversationId?: unknown; language?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const conversationId = typeof body.conversationId === 'string' ? body.conversationId.trim() : '';
  if (!conversationId) {
    return NextResponse.json({ error: 'conversationId is required' }, { status: 400 });
  }

  try {
    const conversation = await db.conversation.findUnique({
      where: { id: conversationId },
      include: { messages: { orderBy: { createdAt: 'asc' } } },
    });
    if (!conversation) {
      return NextResponse.json({ error: 'conversation not found' }, { status: 404 });
    }
    const rows = conversation.messages as unknown as MessageRow[];
    if (rows.length === 0) {
      return NextResponse.json({ error: 'conversation has no messages' }, { status: 404 });
    }

    const lang: Lang = (['en', 'ur', 'roman'] as const).includes(body.language as never)
      ? (body.language as Lang)
      : (conversation.language as Lang) || 'en';

    const transcript = rows
      .map((r) => `${r.role === 'user' ? 'USER' : 'ASSISTANT'}: ${r.content.replace(/\s+/g, ' ').slice(0, 900)}`)
      .join('\n');

    const llmSummary = await llmJSON<unknown>(
      SUMMARY_SYSTEM,
      [`Conversation (may be in English, Urdu or Roman Urdu):\n${transcript}`, '', 'Generate the JSON summary now.'].join('\n'),
      { timeoutMs: 20000 },
    );
    const sanitized = sanitizeSummary(llmSummary, conversationId, lang);

    if (sanitized) {
      return NextResponse.json({ summary: sanitized });
    }
    // LLM failed or produced an invalid/dosed summary → deterministic fallback
    return NextResponse.json({ summary: deterministicSummary(conversationId, rows, lang) });
  } catch {
    return NextResponse.json({ error: 'failed to generate summary' }, { status: 500 });
  }
}
