import { db } from '../src/lib/db';
import { FACILITIES_SEED } from '../src/data/facilities-seed';
import { generateQrMatrix } from '../src/lib/qr';
import type { DoctorSummary } from '../src/lib/types';

let passed = 0;
let failed = 0;

function assert(condition: boolean, msg: string) {
  if (condition) {
    console.log(`  ✅ PASS: ${msg}`);
    passed++;
  } else {
    console.error(`  ❌ FAIL: ${msg}`);
    failed++;
  }
}

async function testDatabaseFacilities() {
  console.log('\n[Group 1] Database Synchronization & Facilities Verification');

  const dbFacilities = await db.facility.findMany();
  console.log(`  Found ${dbFacilities.length} facilities in SQLite database.`);
  
  assert(dbFacilities.length >= 55, `DB facility count >= 55 (actual: ${dbFacilities.length})`);
  assert(dbFacilities.length === FACILITIES_SEED.length, `DB facility count matches seed count (${FACILITIES_SEED.length})`);

  // Verify all supported cities exist
  const cities = ['Lahore', 'Karachi', 'Peshawar', 'Islamabad', 'Multan', 'Rawalpindi', 'Quetta', 'Faisalabad', 'Hyderabad'];
  const dbCities = new Set(dbFacilities.map(f => f.city));
  for (const c of cities) {
    assert(dbCities.has(c), `Database contains facilities for city: ${c}`);
  }

  // Verify Alkhidmat Foundation facilities in database
  const alkhidmatFacilities = dbFacilities.filter(f => f.name.toLowerCase().includes('alkhidmat'));
  console.log(`  Found ${alkhidmatFacilities.length} Alkhidmat Foundation facilities in SQLite database.`);
  assert(alkhidmatFacilities.length >= 20, `Alkhidmat facilities count >= 20 (actual: ${alkhidmatFacilities.length})`);

  // Check Alkhidmat facilities across cities
  const akfCities = new Set(alkhidmatFacilities.map(f => f.city));
  for (const c of ['Lahore', 'Karachi', 'Peshawar', 'Islamabad', 'Multan', 'Rawalpindi', 'Quetta']) {
    assert(akfCities.has(c), `Alkhidmat facility exists in city: ${c}`);
  }

  // Verify coordinates and validity
  for (const f of dbFacilities) {
    if (typeof f.lat !== 'number' || typeof f.lng !== 'number' || isNaN(f.lat) || isNaN(f.lng)) {
      assert(false, `Facility ${f.name} has valid lat/lng coordinates`);
      return;
    }
  }
  assert(true, 'All facilities in database have valid numeric lat/lng coordinates');
}

function testGoogleMapsNavigationUrls() {
  console.log('\n[Group 2] Universal Cross-Platform Google Maps Navigation URLs');

  for (const f of FACILITIES_SEED) {
    const navUrl = `https://www.google.com/maps/search/?api=1&query=${f.lat},${f.lng}`;
    assert(
      navUrl.startsWith('https://www.google.com/maps/search/?api=1&query='),
      `Valid Google Maps URL for ${f.name} (${f.lat}, ${f.lng})`
    );
    // Ensure coordinates are not NaN
    const queryPart = navUrl.split('query=')[1];
    const [latStr, lngStr] = queryPart.split(',');
    assert(!isNaN(parseFloat(latStr)) && !isNaN(parseFloat(lngStr)), `Coordinates valid in URL: ${queryPart}`);
  }
}

function testQrMatrixGeneration() {
  console.log('\n[Group 3] QR Code Matrix Generation (ISO/IEC 18004 Compliant)');

  // Test 1: Short text
  const m1 = generateQrMatrix('Test');
  assert(m1.length >= 21, `Version 1+ matrix generated with size ${m1.length}x${m1.length}`);

  // Test 2: Typical clinical summary text (approx 200-300 chars)
  const clinicalText = `SehatAI — Doctor Summary
Chief complaint: High grade fever with chills
Duration: 3 days
Symptoms: High fever (103F), rigors, severe headache, body aches
Red flags observed: High fever > 102F
Triage level: Urgent (L2)
Guidance given: Visit nearby clinic or hospital for CBC and Malarial Parasite / Dengue NS1 screening. Stay hydrated with ORS. Take paracetamol for fever.
Disclaimer: This summary is generated by SehatAI for clinical context. Always consult a licensed medical professional.`;
  
  const mClinical = generateQrMatrix(clinicalText);
  assert(mClinical.length >= 21, `Clinical summary matrix generated with size ${mClinical.length}x${mClinical.length}`);

  // Test 3: Large clinical summary text (> 500 chars)
  const longClinicalText = clinicalText + '\n' + 'Additional observation notes: Patient reports mild nausea, no vomiting, no bleeding spots, normal urine output. Advised red flag warnings for dengue shock syndrome and immediate 1122 escalation if breathing difficulty occurs.';
  const mLong = generateQrMatrix(longClinicalText);
  assert(mLong.length >= 21, `Long clinical summary matrix generated with size ${mLong.length}x${mLong.length}`);

  // Test 4: Matrix invariants (square, non-empty, boolean values)
  let allBoolean = true;
  for (let r = 0; r < mLong.length; r++) {
    if (mLong[r].length !== mLong.length) {
      allBoolean = false;
      break;
    }
    for (let c = 0; c < mLong[r].length; c++) {
      if (typeof mLong[r][c] !== 'boolean') {
        allBoolean = false;
        break;
      }
    }
  }
  assert(allBoolean, 'QR Matrix is perfectly square and contains only boolean cells');

  // Test 5: Top-left, top-right, bottom-left finder patterns present
  assert(mClinical[0][0] === true, 'Top-left finder outer corner is black');
  assert(mClinical[0][6] === true, 'Top-left finder outer corner is black');
  assert(mClinical[6][0] === true, 'Top-left finder outer corner is black');
  assert(mClinical[6][6] === true, 'Top-left finder outer corner is black');
  assert(mClinical[3][3] === true, 'Top-left finder center is black');
}

function testSummaryModalDataNarrowing() {
  console.log('\n[Group 4] Doctor Summary Modal Data Shape Handling');

  const mockSummary: DoctorSummary = {
    chiefComplaint: 'Chest tightness',
    duration: '2 hours',
    symptoms: ['Chest tightness', 'Shortness of breath'],
    redFlagsObserved: ['Severe chest pain with radiating discomfort'],
    triageLevel: 'EMERGENCY',
    guidanceGiven: ['Call 1122 immediately', 'Do not drive yourself'],
    disclaimer: 'For clinical reference only.',
  };

  // Test unwrapped shape
  const rawDataDirect: DoctorSummary | { summary: DoctorSummary } = mockSummary;
  const sDirect = 'summary' in rawDataDirect && rawDataDirect.summary ? rawDataDirect.summary : (rawDataDirect as DoctorSummary);
  assert(sDirect.chiefComplaint === 'Chest tightness', 'Direct DoctorSummary object unwraps accurately');

  // Test wrapped shape { summary: DoctorSummary }
  const rawDataWrapped: DoctorSummary | { summary: DoctorSummary } = { summary: mockSummary };
  const sWrapped = 'summary' in rawDataWrapped && rawDataWrapped.summary ? rawDataWrapped.summary : (rawDataWrapped as DoctorSummary);
  assert(sWrapped.chiefComplaint === 'Chest tightness', 'Wrapped { summary: DoctorSummary } unwraps accurately');
}

async function main() {
  console.log('============================================================');
  console.log('  SehatAI — Reviewer 2 Comprehensive Verification Suite');
  console.log('============================================================');

  await testDatabaseFacilities();
  testGoogleMapsNavigationUrls();
  testQrMatrixGeneration();
  testSummaryModalDataNarrowing();

  console.log('\n============================================================');
  console.log(`  RESULTS: ${passed} PASSED / ${failed} FAILED`);
  console.log('============================================================\n');

  if (failed > 0) {
    process.exit(1);
  }
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
